global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using System;
global using System.Threading;
global using System.Threading.Channels;
global using System.Threading.Tasks;
global using Grpc.Net.Client;
global using OrderProcess.Server.Services;
global using OrderProcess.Worker;
